# sous-chef/docker-compose.yml

version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.prod  # Use Dockerfile for development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /etc/letsencrypt/live/sous-chef.tech:/etc/letsencrypt/live/sous-chef.tech:ro
      - /etc/letsencrypt/archive/sous-chef.tech:/etc/letsencrypt/archive/sous-chef.tech:ro
    ports:
      - "80:80"
      - "443:443"  # SSL port
    # environment:
    #   - CHOKIDAR_USEPOLLING=true  # For file watching on some environments
    environment:
      - REACT_APP_API_URL=http://sous-chef.tech/api
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.prod  # Use development Dockerfile
    volumes:
      - ./backend:/app
      - /app/venv
    ports:
      - "5050:5050"
    environment:
      - FLASK_ENV=development
      - OPENAI_API_KEY=your_openai_api_key_here  # Consider using a .env file
    command: flask run --host=0.0.0.0 --port=5050

  # Optional: Database service (e.g., PostgreSQL)
  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: sous_chef_db
  #   ports:
  #     - "5432:5432"
