# backend/dockerfile.prod

FROM python:3.9-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install gunicorn

# Copy project
COPY . .

ENV FLASK_APP=App.py

# Expose port
EXPOSE 5050

# Start Gunicorn server
CMD ["gunicorn", "--bind", "0.0.0.0:5050", "App.py"]
