# backend/dockerfile

# Use an official Python runtime as a parent image
FROM python:3.9-alpine

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Install additional dependencies for development
RUN pip install flask flask-cors python-dotenv gunicorn

# Copy project
COPY . .

# Expose the port Flask is running on
# EXPOSE 5050

# Set environment variables for Flask
ENV FLASK_APP=app.py
ENV FLASK_ENV=development

# Start the Flask development server
CMD ["flask", "run", "--host=0.0.0.0"]
# backend/Dockerfile.dev

# Use an official Python runtime as a parent image
FROM python:3.9-alpine

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Install additional dependencies for development
RUN pip install flask flask-cors python-dotenv gunicorn

# Copy project
COPY . .

# Expose the port Flask is running on
EXPOSE 5050

# Set environment variables for Flask
ENV FLASK_APP=App.py
ENV FLASK_ENV=development

# Start the Flask development server
CMD ["flask", "run", "--host=0.0.0.0", "--port=5050"]
